
PLAY [Run the command or configuration on devices] ******************************************************************************************************************************************

TASK [Send a command to Juniper device] *****************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [qfx5120-48y-1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636373.99-26173786400651/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636373.99-26173786400651/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636373.99-26173786400651/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_WAKMJT/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_WAKMJT/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host qfx5120-48y-1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [qfx5120-48y-2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.0-268574013063845/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.0-268574013063845/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.0-268574013063845/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_pe3cJA/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_pe3cJA/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host qfx5120-48y-2 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [qfx5120-48t-1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.02-279800420157969/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.02-279800420157969/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.02-279800420157969/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_xDm2MS/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_xDm2MS/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host qfx5120-48t-1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [qfx5120-48t-2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.03-35548599863631/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.03-35548599863631/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.03-35548599863631/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_DrKVms/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_DrKVms/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host qfx5120-48t-2 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [srx4600-1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.05-128418393849228/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.05-128418393849228/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.05-128418393849228/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_mUUBbd/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_mUUBbd/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host srx4600-1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [srx4600-2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.69-26268805391810/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.69-26268805391810/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.69-26268805391810/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_pQkCj2/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_pQkCj2/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host srx4600-2 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [srx4600-3]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.7-238685287752984/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.7-238685287752984/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.7-238685287752984/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_OZlttq/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_OZlttq/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host srx4600-3 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [srx4200-1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.72-27609217584926/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.72-27609217584926/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.72-27609217584926/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_edajWB/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_edajWB/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host srx4200-1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [srx4200-2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.74-31673579328684/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.74-31673579328684/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.74-31673579328684/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_wdlemJ/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_wdlemJ/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host srx4200-2 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [srx380-1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.75-76629611879208/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.75-76629611879208/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636374.75-76629611879208/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_ohKlv2/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_ohKlv2/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host srx380-1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [srx380-2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.11-59364696757856/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.11-59364696757856/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.11-59364696757856/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_w3ESZA/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_w3ESZA/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host srx380-2 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [srx320-1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.14-43487290437285/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.14-43487290437285/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.14-43487290437285/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_7HKJPX/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_7HKJPX/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host srx320-1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [srx320-2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.15-193304366220811/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.15-193304366220811/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.15-193304366220811/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_xk7Ozi/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_xk7Ozi/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host srx320-2 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [mx204-1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.17-279711495851249/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.17-279711495851249/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.17-279711495851249/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_3K5uJv/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_3K5uJv/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host mx204-1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [mx204-2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.19-34409196433006/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.19-34409196433006/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.19-34409196433006/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_zXJXYG/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_zXJXYG/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host mx204-2 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [nfx150-1]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.51-208023860648582/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.51-208023860648582/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.51-208023860648582/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload__n_jU4/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload__n_jU4/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host nfx150-1 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [nfx150-2]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.54-234838581022543/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.54-234838581022543/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.54-234838581022543/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_TIsiIY/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_TIsiIY/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host nfx150-2 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named plugins.action.normal
fatal: [nfx150-3]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.57-111163522921260/AnsiballZ_juniper_junos_command.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.57-111163522921260/AnsiballZ_juniper_junos_command.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/nlandsberg/.ansible/tmp/ansible-tmp-1617636375.57-111163522921260/AnsiballZ_juniper_junos_command.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_sGzVDY/__main__.py\", line 312, in <module>\n  File \"/var/folders/0h/kbc2wm653njfz31f4wdqj8d80000gn/T/ansible_juniper_junos_command_payload_sGzVDY/ansible_juniper_junos_command_payload.zip/ansible/module_utils/juniper_junos_common.py\", line 39, in <module>\nImportError: No module named plugins.action.normal\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform darwin on host nfx150-3 is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See https://docs.ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information."]}

PLAY RECAP **********************************************************************************************************************************************************************************
mx204-1                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
mx204-2                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
nfx150-1                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
nfx150-2                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
nfx150-3                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
qfx5120-48t-1              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
qfx5120-48t-2              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
qfx5120-48y-1              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
qfx5120-48y-2              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
srx320-1                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
srx320-2                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
srx380-1                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
srx380-2                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
srx4200-1                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
srx4200-2                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
srx4600-1                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
srx4600-2                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
srx4600-3                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

